//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCT_PBB_DailyAircraftDocked
    {
        public System.DateTime DateAndTime { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA2_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA3_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA4_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA6_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA7B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA7F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA8B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA8F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA9B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA9F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA10B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneA_GateA10F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB1_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB2_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB3_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB4B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB4F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB5_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB7B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB7F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB8B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB8F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB9_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB10_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneB_GateB11_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC1_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC2_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC3_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC4_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC6_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC9_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC10B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC10F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC11B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC11F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC12B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC12F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC15_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC16B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_MCT_Term1_ZoneC_GateC16F_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
    }
}
